#pragma once

#define MAXNROFLIGHTS 2
#define EXTRACONSTANTBUFFERVIEWS 4
#define EXTRATEXTUREMATERIALS 1

#define MAXRANGESOFTSHADOWS 5
#define NUMBEROFPOINTSINSOFTSHADOWS 5

#define MAXNROFMATERIALS 256
#define ANYMATERIALBEFOREDEFAULTMATERIAL true